Add API for main extension
NordicPlayground/vscode-kconfig pull request #2
Opened 2021-07-09 12:58 UTC by deerob4

2021-07-12 09:29 UTC, michaeljones commented
It looks broadly ok to me. I'm not confident in reviewing it though.

I'm assuming some of the code that has been removed is stuff that was popping up or happening automatically that made sense for the stand alone extension but not when integrated? 

I'm not sure why the Api class has some methods that are just empty? We don't seem to be implementing an interface or anything so I'm not sure why they exist?

2021-07-12 10:44 UTC, andrerim commented
> I'm not sure why the Api class has some methods that are just empty? We don't seem to be implementing an interface or anything so I'm not sure why they exist?

I'm not sure either, @deerob4 didn't say why. They are either not needed or this isn't actually finished, I will take a deeper look.

2021-07-13 06:37 UTC, trond-snekvik requested changes

2021-07-13 06:37 UTC, trond-snekvik commented on src/api.ts
> +import * as vscode from 'vscode';
Needs license

2021-07-13 06:37 UTC, trond-snekvik commented on src/api.ts
> +        west: string | undefined;
```suggestion
        west?: string;
```
same above

2021-07-13 06:37 UTC, trond-snekvik commented on src/api.ts
> +    }
The ZephyrBoard and KconfigRoot should be tied to the context, like in the devicetree api. Even though there's just support for one context at the moment, we'll need more in the future, each with their own environment

2021-07-13 06:37 UTC, trond-snekvik commented on src/api.ts
> +    } = { kconfigRoot: undefined, zephyrBoard: undefined, west: undefined };
```suggestion
    } = { };
```

2021-07-16 13:48 UTC, trond-snekvik approved these changes

2021-07-16 13:50 UTC, trond-snekvik commented
Ironically, I'm not registered as a member of this repo, so my review doesn't count :smile: Will have to wait for @wbober to come back, unless the rules for this repo doesn't mandate reviews

2021-07-19 06:56 UTC, wbober commented
@trond-snekvik This should be fixed now.

2021-07-20 06:50 UTC, bencefr commented
I don't seem to find use of the introduced context, it only seem to update global configuration. My assumption is that all references to configuration values must be changed to refer to values mandated by the context and only use the configuration as a global fallback, otherwise the context makes no sense. I'd like to hear more from @trond-snekvik .

2021-07-20 09:08 UTC, bencefr approved these changes

2021-07-20 10:19 UTC, merged